app:
  name: GeneReport_platform
  port: :8080
mysql:
  dsn: root:608111@tcp(mysql.r81057260.nyat.app:18023)/GeneReport_platform?charset=utf8mb4&parseTime=True&loc=Local
  MaxIdleConns: 10
  MaxOpenConns: 100
redis:
  addr: "map.r81057260.nyat.app:29125"
  password: "608111"
  timeout: 3000
  db: 0